# Generated by Django 4.2.21 on 2025-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=100)),
                ("f_desc", models.CharField(max_length=255)),
                ("f_type", models.CharField(max_length=100)),
                ("f_price", models.CharField(max_length=100)),
                ("f_image", models.ImageField(upload_to="menu")),
            ],
        ),
    ]
