# Generated by Django 4.2.21 on 2025-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=100)),
                ("f_phone", models.CharField(max_length=10)),
                ("f_email", models.EmailField(max_length=254)),
                ("f_desc", models.CharField(max_length=255)),
            ],
        ),
    ]
